# Generated by Django 4.2 on 2023-09-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_bb__content_rendered_alter_bb_content'),
        ('testapp', '0007_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
